name = input ('Enter your name:')
print ('My name is',name)
email = input ('What is your email address?')
print ('My email address is', email)
username = input ('What is your slack username?')
print ('My slack username is', username)
language = input ('What programming language did you use?')
print ('I wrote my script in',language)
biostack = input ('Enter your biostack')
print ('My biostack is', biostack) 